name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BACKEND_IMAGE: ${{ vars.DOCKER_USERNAME }}/k8s-backend:1.0
      FRONTEND_IMAGE: ${{ vars.DOCKER_USERNAME }}/k8s-frontend:1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          cd k8s-backend
          docker build -t $BACKEND_IMAGE .
          docker push $BACKEND_IMAGE

      - name: Build and push frontend image
        run: |
          cd k8s-frontend
          docker build -t $FRONTEND_IMAGE .
          docker push $FRONTEND_IMAGE

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

#      - name: Deploy to Kubernetes
#        env:
#          KUBECONFIG: ${{ secrets.KUBECONFIG }}
#        run: |
#          sed -i "s|<your_docker_hub_username>|${{ vars.DOCKER_USERNAME }}|g" k8s-backend/backend-deployment.yaml
#          sed -i "s|<your_docker_hub_username>|${{ vars.DOCKER_USERNAME }}|g" k8s-frontend/frontend-deployment.yaml
#          kubectl apply -f k8s-backend/backend-deployment.yaml
#          kubectl apply -f k8s-frontend/frontend-deployment.yaml
